################################################################################
## Releasing the hounds in your local environment.
##
## Setup:
## $ gem install rubocop
##
## Run:
## $ rubocop ./path/to/file ./or/path/to/directory -c ./.hound.yml
##
## Generation Notes:
##   This file was generated via the commitment:install generator. You are free
##   and expected to change this file.
################################################################################
AllCops:
  Include:
    - Rakefile
  Exclude:
    - scripts/**/*
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'db/data/**/*'
  TargetRubyVersion: 2.2

Rails:
  Enabled: true


AbcSize:
  Exclude:
    - app/models/repository_service/identifier_relationship.rb
    - app/models/cogitate/models/identifiers/verified.rb
    - lib/cogitate/models/agent/serializer.rb
    - lib/cogitate/client/agent_builder.rb

MethodLength:
  Exclude:
    - app/models/cogitate/models/identifiers/verified.rb
    - lib/cogitate/models/agent/serializer.rb

LineLength:
  Description: 'Limit lines to 140 characters.'
  Max: 140
  Enabled: true

Style/DoubleNegation:
  Exclude:
    - app/controllers/application_controller.rb

Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  Enabled: false

PercentLiteralDelimiters:
  Description: 'Use `%`-literal delimiters consistently'
  Enabled: false

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: true
  Exclude:
  - spec/**/*
  - test/**/*

Style/WordArray:
  Enabled: false

Style/BracesAroundHashParameters:
  Exclude:
    - lib/cogitate/services/identifiers_decoder.rb

Style/ConstantName:
  Exclude:
    - lib/cogitate/interfaces.rb
