Figaro.require_keys(
  'agent_tokenizer_encryption_type',
  'agent_tokenizer_private_password',
  'agent_tokenizer_public_password',
  'agent_tokenizer_issuer_claim',
  'hesburgh_api_auth_token',
  'hesburgh_api_host',
  'omniauth_cas_url',
  'url_host',
  'cogitate_services_remote_server_base_url'
)
