Figaro.require_keys(
  'cogitate_services_tokenizer_encryption_type',
  'cogitate_services_tokenizer_private_password',
  'cogitate_services_tokenizer_public_password',
  'cogitate_services_tokenizer_issuer_claim',
  'cogitate_services_remote_server_base_url',
  'hesburgh_api_auth_token',
  'hesburgh_api_host',
  'omniauth_cas_url'
)
