development: &development
  domain_name: <%= Figaro.env.domain_name %>
  secret_key_base: <%= Figaro.env.secret_key_base %>

test:
  <<: *development

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  <<: *development

staging:
  <<: *production

pre_production:
  <<: *production
