# Render via PlantUML
# Generated via plantuml-preview (https://github.com/peele/plantuml-preview) in Atom
@startuml

title Sequence Diagram for Cogitate Integration

Browser -> Application : GET /authenticate
Application --> Application : Store :before_authentication_location
Application --> Cogitate : Redirect with\napplication's :after_authentication_callback_url
Cogitate --> "Remote Authentication Service" : Redirect
Browser <- "Remote Authentication Service" : Authentication Form
Browser -> "Remote Authentication Service" : POST Authentication Credentials
Cogitate <-- "Remote Authentication Service" : Redirect
Cogitate <--> "Remote Authentication Service" : Negotiate Authentication Strategy\n(i.e. OAuth 2 handshake)
Application <-- Cogitate : Redirect with ticket\nto :after_authentication_callback_url
Application --> Cogitate : Redeem ticket
Cogitate --> Cogitate : Convert Ticket to Agent Token
Application <-- Cogitate : Send Agent token
Application --> Application : Store Agent in session
Browser <- Application: Redirect to :before_authentication_location

@enduml
